default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: flowchart_development

test:
  <<: *default
  database: flowchart_test

production:
  <<: *default
  database: flowchart_production
  username: flowchart
  password: <%= ENV["FLOWCHART_DATABASE_PASSWORD"] %>
